### ISSUE TITLE
documentation need to add dependencies

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/tomo_raycaster2#1]
I tried to install and this requires Three.js. I think its worthwhile to include this in the README.

**Comment by nicolaisi** [comment]
<script type="text/javascript" src="static/js/libs/threejs/build/three.min.js"></script>
		<script type="text/javascript" src="static/js/OrbitControls.js"></script>
		<script type="text/javascript" src="static/js/libs/tomo_raycaster2/build/volumeRaycaster.js"></script>
		<script type="text/javascript" src="static/js/libs/dat.gui/dat.gui.min.js"></script>
		<script type="text/javascript" src="static/js/dat.gui.helper.js"></script>
		<script type="text/javascript" src="static/js/libs/embeddedjs/ejs.js"></script>

**Comment by sogimu** [comment]
But you have use Bower(http://bower.io) for installing dependencies:

Install it if not yet:
$ sudo zypper in npm
$ sudo npm install
$ sudo npm install -g bower

And use it:
$ bower install
$ bower update

All dependencies (js libraries) will be installed.

For doing it not manualy had created two scripts:
./install_npm_packages.sh
./upload_dependencies.sh

**Comment by nicolaisi** [comment]
Yes, we will need to update this in the README.

**Comment by sogimu** [comment]
ahh, I thought that's it already here. I will add it.
