### ISSUE TITLE
Use a more specific div id for view

### ISSUE THREAD

**Issue by matze** [kit-ipe/tomo_raycaster2#12]
`container` is probably the most generic and worst choice for an id specifying the WebGL view …

**Comment by matze** [comment]
Sorry, just saw that one can specify the id.

**Comment by nicolaisi** [comment]
I think we can keep this open, I remember there's a bug here. Whenever someone specify a different id name, it still takes "container" as the default value. I'll double check on this.

**Comment by matze** [comment]
Yes, it's still the case and it's still annoying because it provokes name clashes. At least prefix that with `wave-container` or something similar.

**Comment by nicolaisi** [comment]
the default id now set to "wave-container"
