### ISSUE TITLE
scoping problem in the callback

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/tomo_raycaster2#2]
Uncaught TypeError: THREE.OrbitControls is not a function

**Comment by nicolaisi** [comment]
It's not the scoping problem, the dependency is missing.

**Comment by stanislavHamara** [comment]
How was this solved?

**Comment by nicolaisi** [comment]
Apparently the readme is not updated, the orbitcontrol js is not included. So its not a scoping problem. What problem you're facing? Is it from this library or its a general scoping problem?

**Comment by nicolaisi** [comment]
I'll update the readme by end of today and you can follow the dependency installation to get this library running.
